### ISSUE TITLE
Missing set_vm_network_adapter_vlan.rb

### ISSUE THREAD

**Issue by ksagle77** [ananace/fog-hyperv#18]
Hey,

After updating to version 0.0.6, I am unable to create or view VMs. The following error is thrown:

![image](https://user-images.githubusercontent.com/34070189/35243260-36efdce8-ff8a-11e7-9d3f-8bffb1fe8b6a.png)

Following error is thrown when testing from command line:

![image](https://user-images.githubusercontent.com/34070189/35244305-b870aaba-ff8d-11e7-9943-31117a92d0ba.png)

Issue is missing file for set_vm_network_adapter_vlan referenced in compute.rb. It works correctly after creating the file.

[kevin@zabbix dev]$ vim fog-hyperv/lib/fog/hyperv/requests/compute/set_vm_network_adapter_vlan.rb
````
module Fog
  module Compute
    class Hyperv
      class Real
        def set_vm_network_adapter_vlan(options = {})
          requires_one options, :vm_name, :management_os
          run_shell('Set-VMNetworkAdapterVlan', options)
        end
      end
    end
  end
end
````
![image](https://user-images.githubusercontent.com/34070189/35244491-4b4a458a-ff8e-11e7-96c1-d7809247943f.png)

Kevin

**Comment by ananace** [comment]
I apparently forgot to add the request file when doing the commit, pushed it now and decided to push a release for that as well.

Are you sure you updated to 0.0.6 though? Because that request was added on the commit after the version tag.

Either way, this issue should be solved, thanks.

**Comment by ksagle77** [comment]
Hey,

Sorry, yea I had updated from git not from the gem.

Thanks,

Kevin
