### ISSUE TITLE
error when examine VM on hyper-v

### ISSUE THREAD

**Issue by rudgab** [ananace/fog-hyperv#20]
Hi, 
I see a  
Oops, we're sorry but something went wrong undefined method `start_with?' for :id:Symbol

details:

undefined method `start_with?' for :id:Symbol
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/hyperv/compute.rb:240:in `block in run_shell'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/hyperv/compute.rb:240:in `delete_if'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/hyperv/compute.rb:240:in `run_shell'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/hyperv/requests/compute/get_vm.rb:6:in `get_vm'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/collection.rb:20:in `all'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/collection.rb:27:in `get'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fog-hyperv-0.0.7/lib/fog/hyperv/models/compute/servers.rb:16:in `get'
/usr/share/foreman/app/models/compute_resource.rb:173:in `find_vm_by_uuid'

whenever I enter a VM from the table of virtual machines on any Hyper-V host.

Regards,

Rudi G.

**Comment by ananace** [comment]
This looks like the same as #19, could you please test if the commits there solve your issue as well?

**Comment by rudgab** [comment]
Yes, the problem is solved by that.

Thanx,

R.G.
